name: rust-api-service

services:
  backend:
    restart: always
    build: .
    environment:
      - RUST_LOG=debug
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data


volumes:
  db-data: {}
