[server]
port = 8000

[db]
url = "postgresql://test:test@db:5432/test"

[logger]
level = "info"

[storage]
endpoint = "http://storage:9000"
bucket = "profile-images"
access_key = "miniominio"
secret_key = "secretsecret"
