[server]
addr = "0.0.0.0:8000"

[db]
url = "postgresql://test:test@db:5432/test"

[logger]
level = "info"

[storage]
endpoint = "http://localhost:9000"
bucket = "profile-images"
access_key = "miniominio"
secret_key = "secretsecret"
