[server]
addr = "0.0.0.0:80"

[db]
url = "postgresql://tweeter:tweeter@db:5432/tweeter"

[logger]
level = "info"

[storage]
endpoint = "http://localhost:9000"
bucket = "profile-images"
access_key = "miniominio"
secret_key = "secretsecret"
