[server]
port = 8080

[db]
url = "postgresql://test:test@localhost:5432/test"

[logger]
level = "info"

[storage]
endpoint = "http://localhost:9000"
bucket = "profile-images"
access_key = "miniominio"
secret_key = "secretsecret"
