name: tweeter

services:
  backend:
    image: velnbur/tweeter-backend:latest
    build:
      context: ..
      dockerfile: ./tweeter-backend/Dockerfile
    environment:
      - RUST_LOG=debug
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: ./backend.toml
        target: /etc/config.yaml
        read_only: true
    entrypoint: ["service", "--config", "/etc/config.yaml"]

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/profile-images && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=secretsecret
      - MINIO_BROWSER=on
    volumes:
      - storage-data:/data
    ports:
      - "9000:9000"

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 8080:8080
    depends_on:
      - backend

volumes:
  db-data: {}
  storage-data: {}
