name: tweeter

services:
  #  frontend:
  #    image: ghcr.io/velnbur/tweeter-frontend:master
  #    depends_on:
  #- backend

  backend:
    image: ghcr.io/velnbur/tweeter-backend:master
    depends_on:
      - db
      - storage
    volumes:
      - type: bind
        source: ./backend.toml
        target: /etc/config.yaml
        read_only: true
    entrypoint:
      [
        "service",
        "--config",
        "/etc/config.yaml",
        "--migrate"
      ]

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=tweeter
      - POSTGRES_USER=tweeter
      - POSTGRES_DB=tweeter
    volumes:
      - db-data:/var/lib/postgresql/data

  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/profile-images && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=tweetertweeter
    volumes:
      - storage-data:/data

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - backend
    # - frontend

volumes:
  db-data: {}
  storage-data: {}
