name: rust-api-service

services:
  backend:
    restart: always
    build: ./tweeter-backend
    environment:
      - RUST_LOG=debug
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=test
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  storage:
    image: minio/minio:RELEASE.2019-01-31T00-31-19Z
    restart: unless-stopped
    entrypoint: "sh"
    command: -c "mkdir -p /data/profile-images && minio server /data"
    environment:
      - MINIO_ACCESS_KEY=miniominio
      - MINIO_SECRET_KEY=secretsecret
      - MINIO_BROWSER=on
    volumes:
      - storage-data:/data
    ports:
      - "9000:9000"

volumes:
  db-data: {}
  storage-data: {}
